# Generated by Django 4.2.2 on 2023-07-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('author', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=20)),
                ('pdf', models.FileField(null=True, upload_to='pdfs')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_issued', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'book_detail',
                'verbose_name_plural': 'book_details',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('pdf', models.FileField(upload_to='pdfs')),
            ],
            options={
                'verbose_name': 'newspaper',
                'verbose_name_plural': 'newspapers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('on', models.DateTimeField(verbose_name='Date and Time')),
                ('location', models.CharField(max_length=250)),
                ('inauguration', models.CharField(max_length=250)),
                ('welcome_speech', models.CharField(max_length=250)),
                ('presidential_speech', models.CharField(max_length=250)),
                ('greetings', models.CharField(max_length=250)),
                ('special_speech', models.CharField(max_length=250, null=True)),
                ('speech', models.CharField(max_length=250)),
                ('song', models.CharField(max_length=250)),
                ('vote_of_thanks', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('phone', models.IntegerField()),
                ('gmail', models.EmailField(max_length=254)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'patron',
                'verbose_name_plural': 'patrons',
                'ordering': ('card_no',),
            },
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('returned', models.BooleanField(default=False)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.book_details')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.patron')),
            ],
        ),
        migrations.AddField(
            model_name='book_details',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.category'),
        ),
        migrations.AddField(
            model_name='book_details',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylibrary.patron'),
        ),
        migrations.AddField(
            model_name='book_details',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.language'),
        ),
    ]
