# Generated by Django 4.2.2 on 2023-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='on',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
